version: "3.7"
services:
    mongodb:
        image: 3.4.23
        container_name: "mongodb"
        ports:
          - 27017:27017
        command: --smallfiles
    app:
       image: spring-boot-mongo/shop-item
       ports:
         - 8080:8080
       links:
         - mongodb