version: '3'
services:
    mongo:
        container_name: mongo
        image: mongo
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017

    app:
        restart: always
        build: ./app
        working_dir: /app
        volumes:
            - ./app:/app
            - ~/.m2:/root/.m2
        expose:
            - "8080"
        command: mvn clean spring-boot:run
        depends_on:
            - mongo
        network_mode: host